user-subscription:
  host: "localhost"
  port: "8082"
  basepath: "api"
  protocol: "HTTP"
  responseTimeout: "300000"
  advanceNotificationMins: "120"
  
identity-management:
  host: "localhost"
  port: "8083"
  basepath: "api"
  protocol: "HTTP"
  responseTimeout: "300000"
  apiClientKey : "2f9f2d34-cf0d-44d0-bac3-636182f402db"
  apiClientSecret : "921867d0-f78f-4137-aa21-b21bdf0590bc"
  oktaClientKey : "0oaam2ymcSSrvuWM94x6"
  oktaClientSecret : "g9Sw0N_ZO_embX9nAX3GwX_6vhFNgiGQUiPjQsx3"
http:
  port: "8081"