[
  {
    "SOURCE_LOCATION": "BSK",
    "ADVANCE_NOTIFICATION_TIME_MIN": 57,
    "DESTINATION_LOCATION": "DBC"
  },
  {
    "SOURCE_LOCATION": "BSK",
    "ADVANCE_NOTIFICATION_TIME_MIN": 117,
    "DESTINATION_LOCATION": "WAT"
  }
]