subscription:
  host: "localhost"
  port: "8082"
  basepath: "api"
  protocol: "HTTP"
  responseTimeout: "10000"
  advanceNotificationMins: "120"
rail:
  host: "localhost"
  port: "8084"
  basepath: "api"
  protocol: "HTTP"
  responseTimeout: "10000"
salesforce:
  authURL: "https://login.salesforce.com/services/Soap/u/46.0"
  securityToken: "Gxq9brmkLmP2SJpaqVnKsXGCu"
  username: "nationalrailalert@gmail.com"
  password: "S@les32!"
http:
  port: "8085"
  